SOLID_BLOCK = 'X'
STRUCTURE_1 = '/'
STRUCTURE_2 = '\\'
ENEMY = '#'
SWITCH = '*'
SPIKE = '^'

FLAW_NO_FLAW = 'no_flaw'
FLAW_NO_SPIKE = 'no_spike'
FLAW_NO_HAZARD = 'no_hazard'
FLAW_NO_SPEED = 'no_speed'
